### ISSUE TITLE
Arithmatic Exception When Multiple DefaltPicker Implemented in same layout

### ISSUE THREAD

**Issue by jinkalpatelshivalik** [Ramotion/direct-select-android#12]
It gives runtime error when implement more than 1 basic default picker in same activity. Here is log:

java.lang.ArithmeticException: divide by zero
        at com.ramotion.directselect.DSListView.onWindowFocusChanged(DSListView.java:173)
        at android.view.View.dispatchWindowFocusChanged(View.java:13688)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1480)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1484)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1484)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1484)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1484)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1484)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1484)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1484)
        at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:2870)
        at android.view.ViewRootImpl.access$1100(ViewRootImpl.java:142)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4533)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by golovin47** [comment]
Hi @jinkalpatelshivalik. Couldn't reproduce that issue. Also it's absolutely doesn't matter how many lists you have in activity, fragment or view. What matters is how you implement it. Try checking code in example apps in this repo and also Readme section.
