### ISSUE TITLE
How to get selected item's Name(Value)?

### ISSUE THREAD

**Issue by SamakFOX** [Ramotion/direct-select-android#13]
I am about to change the array of the second Direct-Select according to my selection in the first Direct-Select. I tried to send the selected value from 'onSelect' of the PickerBox class to the main class. then, Second Direct-Select doesn't change & occur error message . Could you give me a hint?

I'm on this Error
2020-04-06 01:38:56.408 22110-22110/com.ramotion.directselect.examples.advenced E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ramotion.directselect.examples.advenced, PID: 22110
    java.lang.IllegalStateException: System services not available to Activities before onCreate()
        at android.app.Activity.getSystemService(Activity.java:6136)
        at android.view.LayoutInflater.from(LayoutInflater.java:229)
        at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:212)
        at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:206)
        at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:192)
        at com.ramotion.directselect.examples.advanced.AdvancedExampleCountryAdapter.<init>(AdvancedExampleCountryAdapter.java:22)

**Comment by golovin47** [comment]
Hi, @ZHENAnet. There is some action that you try to do before Activity onCreate method was invoked.
